# Generated by Django 5.2.7 on 2025-11-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CreditoConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('porcentaje_maximo_mensual', models.DecimalField(decimal_places=2, help_text='Porcentaje máximo mensual del cupo (ej. 8.00 = 8 %).', max_digits=5)),
                ('periodo_inicial', models.PositiveIntegerField()),
                ('periodo_final', models.PositiveIntegerField()),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, help_text='Tasa nominal anual en porcentaje (ej. 12.00 = 12 %).', max_digits=5)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credito_constructor', to='PruebaTecnica.proyecto')),
            ],
            options={
                'ordering': ['proyecto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subetapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio_ventas', models.DateField(blank=True, null=True)),
                ('fecha_fin_ventas', models.DateField(blank=True, null=True)),
                ('fecha_inicio_construccion', models.DateField(blank=True, null=True)),
                ('fecha_fin_construccion', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subetapas', to='PruebaTecnica.proyecto')),
            ],
            options={
                'ordering': ['proyecto__nombre', 'nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='DesembolsoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo_despues_del_desembolso', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes_generado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago_capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desembolsos', to='PruebaTecnica.creditoconstructor')),
            ],
            options={
                'ordering': ['periodo'],
                'unique_together': {('credito', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='AporteCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('flujo_caja_apalancado', models.DecimalField(decimal_places=2, help_text='Flujo neto después de considerar el aporte del periodo.', max_digits=14)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_capital', to='PruebaTecnica.proyecto')),
            ],
            options={
                'ordering': ['periodo'],
                'unique_together': {('proyecto', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveIntegerField(help_text='Número consecutivo del mes dentro del proyecto.')),
                ('concepto', models.CharField(choices=[('ingresos', 'Ingresos'), ('costos', 'Costos')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('subetapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='PruebaTecnica.subetapa')),
            ],
            options={
                'ordering': ['subetapa__proyecto__nombre', 'subetapa__nombre', 'periodo', 'concepto'],
                'unique_together': {('subetapa', 'periodo', 'concepto')},
            },
        ),
    ]
