# Generated by Django 5.2.7 on 2025-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PruebaTecnica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subetapa',
            name='fecha_fin_construccion',
        ),
        migrations.RemoveField(
            model_name='subetapa',
            name='fecha_fin_ventas',
        ),
        migrations.RemoveField(
            model_name='subetapa',
            name='fecha_inicio_construccion',
        ),
        migrations.RemoveField(
            model_name='subetapa',
            name='fecha_inicio_ventas',
        ),
        migrations.AddField(
            model_name='subetapa',
            name='periodo_fin_construccion',
            field=models.PositiveIntegerField(blank=True, help_text='Último periodo con costos registrados.', null=True),
        ),
        migrations.AddField(
            model_name='subetapa',
            name='periodo_fin_ventas',
            field=models.PositiveIntegerField(blank=True, help_text='Último periodo con ingresos registrados.', null=True),
        ),
        migrations.AddField(
            model_name='subetapa',
            name='periodo_inicio_construccion',
            field=models.PositiveIntegerField(blank=True, help_text='Periodo inicial en el que se registran costos.', null=True),
        ),
        migrations.AddField(
            model_name='subetapa',
            name='periodo_inicio_ventas',
            field=models.PositiveIntegerField(blank=True, help_text='Periodo inicial (mes consecutivo) en el que se registran ingresos.', null=True),
        ),
    ]
